title: "Bibek Acharya"
author: "Bibek Acharya"
description: "University of Florida"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Resume", file: "https://github.com/bibek365/bibek365.github.io/blob/b51a50a6383442f69846e007c4c8af242fd8312c/Resume.pdf"}
  - {title: "Media", file: "Media.md", icon = "media"}
  - {title: "Gallery", file: "Gallery.md", icon = "picture"}
  - {title: "Contact", file: "Contact.md", icon = "contact"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:bibekacharya@ufl.edu"}
  - {title: Github, icon: github, url: "https://bibek365.github.io"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/bibekUF"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/bbkacharya/"}
  - {title: Google, icon: Google, url: "https://scholar.google.com/citations?user=k5Fv3cMAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
